import type { Db, ML } from "./types";

const m = (en: string, fr: string, ar: string): ML => ({ en, fr, ar });

export function seedDb(): Db {
  return {
    version: 1,
    settings: {
      siteName: "FLUXMEDIA",
      tagline: m("AI Automation & Social Media Management", "Automatisation IA & gestion des réseaux sociaux", "أتمتة بالذكاء الاصطناعي وإدارة وسائل التواصل"),
      contactEmail: "hello@fluxmedia.agency",
      whatsapp: "+212 6 00 00 00 00",
      address: m("Beni Mellal, Morocco", "Béni Mellal, Maroc", "بني ملال، المغرب"),
      footerNote: m("Less manual work. Better systems. Stronger online presence.", "Moins de travail manuel. De meilleurs systèmes. Une présence plus forte.", "عمل يدوي أقل. أنظمة أفضل. حضور أقوى."),
    },
    navigation: [
      { id: "n1", label: m("Home", "Accueil", "الرئيسية"), href: "/", order: 1, active: true },
      { id: "n2", label: m("Automations", "Automatisation", "الأتمتة"), href: "/automations", order: 2, active: true },
      { id: "n3", label: m("Social Media", "Réseaux sociaux", "التواصل الاجتماعي"), href: "/social-media", order: 3, active: true },
      { id: "n4", label: m("About", "À propos", "من نحن"), href: "/about", order: 4, active: true },
      { id: "n5", label: m("Social", "Social", "روابطنا"), href: "/social", order: 5, active: true },
    ],
    categories: [
      { id: "c1", slug: "lead-generation", name: m("Lead Generation", "Génération de leads", "توليد العملاء"), order: 1, active: true },
      { id: "c2", slug: "crm", name: m("CRM", "CRM", "CRM"), order: 2, active: true },
      { id: "c3", slug: "whatsapp", name: m("WhatsApp", "WhatsApp", "واتساب"), order: 3, active: true },
      { id: "c4", slug: "customer-support", name: m("Customer Support", "Support client", "دعم العملاء"), order: 4, active: true },
      { id: "c5", slug: "email", name: m("Email", "E-mail", "البريد الإلكتروني"), order: 5, active: true },
      { id: "c6", slug: "ecommerce", name: m("E-commerce", "E-commerce", "التجارة الإلكترونية"), order: 6, active: true },
      { id: "c7", slug: "appointments", name: m("Appointments", "Rendez-vous", "المواعيد"), order: 7, active: true },
      { id: "c8", slug: "content", name: m("Content", "Contenu", "المحتوى"), order: 8, active: true },
      { id: "c9", slug: "ai-assistants", name: m("AI Assistants", "Assistants IA", "مساعدات ذكية"), order: 9, active: true },
      { id: "c10", slug: "internal-operations", name: m("Internal Operations", "Opérations internes", "العمليات الداخلية"), order: 10, active: true },
    ],
    automations: [
      {
        id: "a1", slug: "instagram-dm-lead-automation", category: "lead-generation", icon: "message",
        title: m("Instagram DM Automation", "Automatisation des DM Instagram", "أتمتة رسائل إنستغرام"),
        short: m("Capture and qualify leads from Instagram conversations automatically.", "Capturez et qualifiez automatiquement les leads venus des conversations Instagram.", "التقط العملاء من محادثات إنستغرام وأهّلهم تلقائيًا."),
        description: m("When someone comments or messages your Instagram, the system replies instantly, asks the right questions, qualifies the lead, and pushes it into your CRM with full context.", "Quand quelqu'un commente ou écrit sur Instagram, le système répond instantanément, pose les bonnes questions, qualifie le lead et l'envoie dans votre CRM avec tout le contexte.", "عندما يعلّق أحدهم أو يراسلك على إنستغرام، يرد النظام فورًا ويطرح الأسئلة المناسبة ويؤهّل العميل ويرسله إلى CRM مع كامل السياق."),
        benefits: [m("Instant replies, 24/7", "Réponses instantanées, 24/7", "ردود فورية على مدار الساعة"), m("No lead left unread", "Aucun lead sans réponse", "لا يبقى عميل بلا رد"), m("Clean CRM records", "Fiches CRM propres", "سجلات CRM نظيفة")],
        workflow: [m("Comment / DM", "Commentaire / DM", "تعليق / رسالة"), m("AI reply & questions", "Réponse IA & questions", "رد ذكي وأسئلة"), m("Lead qualification", "Qualification", "تأهيل العميل"), m("CRM update", "Mise à jour CRM", "تحديث CRM"), m("Sales notification", "Notification vente", "إشعار المبيعات")],
        integrations: ["Instagram", "OpenAI", "HubSpot", "Slack"], order: 1, active: true,
      },
      {
        id: "a2", slug: "website-form-to-crm", category: "lead-generation", icon: "clipboard",
        title: m("Form-to-CRM Pipeline", "Pipeline formulaire vers CRM", "ربط النماذج بـ CRM"),
        short: m("Every website form becomes a qualified, routed CRM record.", "Chaque formulaire web devient une fiche CRM qualifiée et routée.", "كل نموذج على موقعك يصبح سجل CRM مؤهلًا وموجهًا."),
        description: m("Website forms are validated, enriched, scored, and routed to the right pipeline and owner — with instant WhatsApp or email alerts for hot leads.", "Les formulaires sont validés, enrichis, notés et routés vers le bon pipeline et le bon propriétaire — avec alertes WhatsApp ou e-mail pour les leads chauds.", "تُتحقق من النماذج وتُثري وتُقيَّم وتوجَّه إلى المسار والمسؤول الصحيح — مع تنبيهات فورية على واتساب أو البريد للعملاء الساخنين."),
        benefits: [m("Zero manual data entry", "Zéro saisie manuelle", "لا إدخال يدوي للبيانات"), m("Hot leads alerted instantly", "Leads chauds signalés aussitôt", "تنبيه فوري للعملاء الساخنين"), m("Full attribution", "Attribution complète", "تتبع كامل للمصدر")],
        workflow: [m("Website form", "Formulaire web", "نموذج الموقع"), m("Validation & scoring", "Validation & score", "تحقق وتقييم"), m("CRM pipeline", "Pipeline CRM", "مسار CRM"), m("Owner assignment", "Assignation", "تعيين المسؤول"), m("WhatsApp alert", "Alerte WhatsApp", "تنبيه واتساب")],
        integrations: ["Next.js", "HubSpot", "Zoho", "WhatsApp"], order: 2, active: true,
      },
      {
        id: "a3", slug: "whatsapp-business-automation", category: "whatsapp", icon: "whatsapp",
        title: m("WhatsApp Business Automation", "Automatisation WhatsApp Business", "أتمتة واتساب للأعمال"),
        short: m("Auto-replies, catalogs, order updates and follow-ups on WhatsApp.", "Réponses automatiques, catalogues, suivis de commande et relances sur WhatsApp.", "ردود تلقائية وكتالوجات وتحديثات طلبات ومتابعات على واتساب."),
        description: m("A structured WhatsApp system: keyword menus, AI answers, human handoff, and scheduled follow-ups — so your business replies in seconds, not hours.", "Un système WhatsApp structuré : menus par mots-clés, réponses IA, transfert humain et relances planifiées — votre entreprise répond en secondes, pas en heures.", "نظام واتساب منظم: قوائم كلمات مفتاحية وردود ذكية وتحويل للبشر ومتابعات مجدولة — ليرد نشاطك في ثوانٍ لا ساعات."),
        benefits: [m("Seconds-fast responses", "Réponses en quelques secondes", "استجابة خلال ثوانٍ"), m("Structured conversations", "Conversations structurées", "محادثات منظمة"), m("Automatic follow-ups", "Relances automatiques", "متابعات تلقائية")],
        workflow: [m("Customer message", "Message client", "رسالة عميل"), m("Keyword / AI routing", "Routage mot-clé / IA", "توجيه ذكي"), m("Answer or handoff", "Réponse ou transfert", "رد أو تحويل"), m("CRM note", "Note CRM", "ملاحظة CRM"), m("Scheduled follow-up", "Relance planifiée", "متابعة مجدولة")],
        integrations: ["WhatsApp API", "OpenAI", "Notion"], order: 3, active: true,
      },
      {
        id: "a4", slug: "crm-pipeline-automation", category: "crm", icon: "database",
        title: m("CRM Pipeline Automation", "Automatisation du pipeline CRM", "أتمتة مسار CRM"),
        short: m("Stages, tasks and reminders that update themselves.", "Étapes, tâches et rappels qui se mettent à jour seuls.", "مراحل ومهام وتذكيرات تحدّث نفسها بنفسها."),
        description: m("Deals move stages automatically based on activity, tasks are created for the team, and stale deals trigger win-back sequences — your CRM stays alive without data entry.", "Les offres changent d'étape selon l'activité, les tâches sont créées pour l'équipe, et les offres dormantes déclenchent des séquences de reconquête — votre CRM reste vivant sans saisie.", "تنتقل الصفقات بين المراحل حسب النشاط، وتُنشأ المهام للفريق، وتطلق تسلسلات استرجاع للصفحات الراكدة — يبقى CRM حيًا بلا إدخال يدوي."),
        benefits: [m("Always-current pipeline", "Pipeline toujours à jour", "مسار محدث دائمًا"), m("No forgotten deals", "Aucune offre oubliée", "لا صفقات منسية"), m("Team accountability", "Responsabilité d'équipe", "مسؤولية واضحة للفريق")],
        workflow: [m("Deal activity", "Activité de l'offre", "نشاط الصفقة"), m("Stage rules", "Règles d'étapes", "قواعد المراحل"), m("Task creation", "Création de tâches", "إنشاء مهام"), m("Stale-deal win-back", "Reconquête", "استرجاع الراكد"), m("Manager digest", "Synthèse manager", "ملخص للمدير")],
        integrations: ["HubSpot", "Pipedrive", "Zoho", "Slack"], order: 4, active: true,
      },
      {
        id: "a5", slug: "email-follow-up-sequences", category: "email", icon: "mail",
        title: m("Email Follow-up Sequences", "Séquences de relance e-mail", "تسلسلات متابعة بالبريد"),
        short: m("Nurture, follow-up and win-back emails that send themselves.", "E-mails de nurturing, relance et reconquête envoyés automatiquement.", "رسائل رعاية ومتابعة واسترجاع تُرسل تلقائيًا."),
        description: m("Behavior-triggered sequences keep every prospect warm: welcome flows, proposal follow-ups, and win-back campaigns with personalization and clean deliverability.", "Des séquences déclenchées par le comportement gardent chaque prospect chaud : bienvenue, relance de devis, reconquête — avec personnalisation et bonne délivrabilité.", "تسلسلات تُطلق بالسلوك تُبقي كل عميل محتمل مهتمًا: ترحيب ومتابعة عروض واسترجاع — مع تخصيص وقابلية توصيل نظيفة."),
        benefits: [m("Consistent follow-up", "Relance régulière", "متابعة منتظمة"), m("Personalized at scale", "Personnalisation à l'échelle", "تخصيص على نطاق واسع"), m("Higher reply rates", "Taux de réponse plus élevés", "معدلات رد أعلى")],
        workflow: [m("Trigger event", "Événement déclencheur", "حدث مُطلق"), m("Segment selection", "Segmentation", "اختيار الشريحة"), m("Personalized send", "Envoi personnalisé", "إرسال مخصص"), m("Open / click tracking", "Suivi ouvertures", "تتبع الفتح والنقر"), m("Sales handoff", "Transfert aux ventes", "تسليم للمبيعات")],
        integrations: ["Brevo", "Mailchimp", "Resend", "HubSpot"], order: 5, active: true,
      },
      {
        id: "a6", slug: "ai-customer-support", category: "customer-support", icon: "bot",
        title: m("AI Customer Support", "Support client par IA", "دعم عملاء بالذكاء الاصطناعي"),
        short: m("An AI assistant that resolves FAQs and escalates with context.", "Un assistant IA qui résout les FAQ et transfère avec contexte.", "مساعد ذكي يحل الأسئلة الشائعة ويصعّد مع السياق."),
        description: m("Trained on your docs and policies, the assistant answers instantly on web and WhatsApp, and hands complex cases to your team with a full conversation summary.", "Entraîné sur vos documents, l'assistant répond instantanément sur le web et WhatsApp, et transfère les cas complexes avec un résumé complet de la conversation.", "مدرّب على مستنداتك، يجيب فورًا على الويب وواتساب، ويحوّل الحالات المعقدة لفريقك مع ملخص كامل للمحادثة."),
        benefits: [m("80% of FAQs auto-resolved", "80 % des FAQ résolues", "حل 80% من الأسئلة تلقائيًا"), m("Human handoff with context", "Transfert humain avec contexte", "تحويل بشري مع السياق"), m("Support while you sleep", "Support pendant votre sommeil", "دعم حتى أثناء نومك")],
        workflow: [m("Customer question", "Question client", "سؤال عميل"), m("Knowledge retrieval", "Recherche de connaissances", "استرجاع المعرفة"), m("AI answer", "Réponse IA", "رد ذكي"), m("Confidence check", "Contrôle de confiance", "فحص الثقة"), m("Human escalation", "Escalade humaine", "تصعيد بشري")],
        integrations: ["OpenAI", "WhatsApp", "Intercom", "Notion"], order: 6, active: true,
      },
      {
        id: "a7", slug: "appointment-booking-system", category: "appointments", icon: "calendar",
        title: m("Appointment Booking System", "Système de prise de rendez-vous", "نظام حجز المواعيد"),
        short: m("Self-booking, reminders and no-show recovery on autopilot.", "Réservation autonome, rappels et récupération des absences en pilote automatique.", "حجز ذاتي وتذكيرات واستعادة المواعيد الفائتة تلقائيًا."),
        description: m("Clients book themselves into your real availability. The system confirms, reminds, reschedules, and fills cancellations automatically.", "Vos clients réservent selon vos disponibilités réelles. Le système confirme, rappelle, reprogramme et comble les annulations automatiquement.", "يحجز عملاؤك وفق توفرّك الحقيقي. يؤكد النظام ويذكّر ويعيد الجدولة ويملأ الإلغاءات تلقائيًا."),
        benefits: [m("Fewer no-shows", "Moins d'absences", "غيابات أقل"), m("Calendar always synced", "Agenda toujours synchronisé", "تقويم متزامن دائمًا"), m("Zero phone tag", "Fin des allers-retours téléphoniques", "لا مكالمات ذهابًا وإيابًا")],
        workflow: [m("Booking request", "Demande de RDV", "طلب موعد"), m("Availability check", "Vérification des créneaux", "فحص التوفر"), m("Confirmation", "Confirmation", "تأكيد"), m("Smart reminders", "Rappels intelligents", "تذكيرات ذكية"), m("No-show recovery", "Récupération", "استعادة الفائت")],
        integrations: ["Google Calendar", "Cal.com", "WhatsApp"], order: 7, active: true,
      },
      {
        id: "a8", slug: "ecommerce-abandoned-cart", category: "ecommerce", icon: "cart",
        title: m("Abandoned Cart Recovery", "Récupération de paniers abandonnés", "استعادة السلات المتروكة"),
        short: m("WhatsApp and email flows that recover lost carts.", "Flux WhatsApp et e-mail qui récupèrent les paniers perdus.", "مسارات واتساب وبريد تستعيد السلات المتروكة."),
        description: m("When a cart is abandoned, timed WhatsApp and email sequences with incentives bring buyers back — tracked end-to-end in your analytics.", "Quand un panier est abandonné, des séquences WhatsApp et e-mail chronométrées ramènent les acheteurs — suivi de bout en bout dans vos analyses.", "عند ترك سلة، تعيد تسلسلات واتساب وبريد موقوتة المشترين — مع تتبع كامل في تحليلاتك."),
        benefits: [m("Recover lost revenue", "Récupérez du chiffre perdu", "استرجاع إيرادات ضائعة"), m("Timed, not spammy", "Chronométré, non intrusif", "موقوت وغير مزعج"), m("Full funnel visibility", "Visibilité complète du tunnel", "رؤية كاملة للمسار")],
        workflow: [m("Cart abandoned", "Panier abandonné", "سلة متروكة"), m("1h WhatsApp nudge", "Relance WhatsApp 1 h", "تنبيه واتساب بعد ساعة"), m("24h email + offer", "E-mail 24 h + offre", "بريد بعد يوم مع عرض"), m("Checkout tracking", "Suivi du paiement", "تتبع الدفع"), m("Revenue report", "Rapport de revenus", "تقرير الإيرادات")],
        integrations: ["Shopify", "WooCommerce", "WhatsApp", "Brevo"], order: 8, active: true,
      },
      {
        id: "a9", slug: "ai-content-repurposing", category: "content", icon: "sparkles",
        title: m("Content Repurposing Pipeline", "Pipeline de réutilisation de contenu", "خط إعادة تدوير المحتوى"),
        short: m("One long-form piece becomes a week of posts — drafted by AI, approved by you.", "Un contenu long devient une semaine de publications — rédigé par l'IA, validé par vous.", "محتوى طويل يصبح أسبوع منشورات — يحرّرها الذكاء الاصطناعي وتعتمدها أنت."),
        description: m("Feed the pipeline a video, podcast, or article; it outputs platform-native drafts, captions, and hooks into your approval queue and scheduler.", "Donnez une vidéo, un podcast ou un article ; le pipeline produit des brouillons adaptés à chaque plateforme, légendes et accroches, dans votre file de validation.", "أدخل فيديو أو بودكاست أو مقالًا؛ ينتج الخط مسودات ملائمة لكل منصة مع تعليقات وافتتاحيات في قائمة الاعتماد والجدولة."),
        benefits: [m("10x output from one asset", "10x plus de contenu par asset", "عشرة أضعاف المحتوى من أصل واحد"), m("Platform-native drafts", "Brouillons adaptés par plateforme", "مسودات ملائمة لكل منصة"), m("Human approval built in", "Validation humaine intégrée", "اعتماد بشري مدمج")],
        workflow: [m("Source upload", "Upload de la source", "رفع المصدر"), m("AI transcription", "Transcription IA", "نسخ ذكي"), m("Draft generation", "Génération de brouillons", "توليد مسودات"), m("Approval queue", "File de validation", "قائمة الاعتماد"), m("Auto-scheduling", "Planification auto", "جدولة تلقائية")],
        integrations: ["OpenAI", "Notion", "Meta", "Buffer"], order: 9, active: true,
      },
      {
        id: "a10", slug: "internal-ai-assistant", category: "ai-assistants", icon: "cpu",
        title: m("Internal AI Assistant", "Assistant IA interne", "مساعد ذكي داخلي"),
        short: m("A private assistant trained on your company knowledge.", "Un assistant privé entraîné sur les connaissances de votre entreprise.", "مساعد خاص مدرّب على معرفة شركتك."),
        description: m("Your team asks, the assistant answers from your SOPs, docs and past decisions — with sources. Onboarding new staff becomes days, not months.", "Votre équipe pose ses questions, l'assistant répond à partir de vos procédures et documents — avec sources. Intégrer un nouveau devient une affaire de jours.", "يسأل فريقك ويجيب المساعد من إجراءاتك ومستنداتك — مع المصادر. فيصبح دمج موظف جديد مسألة أيام لا أشهر."),
        benefits: [m("Answers with sources", "Réponses avec sources", "إجابات بمصادر"), m("Faster onboarding", "Intégration accélérée", "دمج أسرع"), m("Knowledge never lost", "Savoir jamais perdu", "معرفة لا تضيع")],
        workflow: [m("Team question", "Question d'équipe", "سؤال الفريق"), m("Doc retrieval", "Recherche documentaire", "استرجاع المستندات"), m("Grounded answer", "Réponse fondée", "إجابة موثقة"), m("Source links", "Liens sources", "روابط المصادر"), m("Feedback loop", "Boucle de feedback", "حلقة تغذية راجعة")],
        integrations: ["OpenAI", "Notion", "Google Drive", "Slack"], order: 10, active: true,
      },
      {
        id: "a11", slug: "automated-weekly-reporting", category: "internal-operations", icon: "chart",
        title: m("Automated Weekly Reporting", "Rapports hebdomadaires automatisés", "تقارير أسبوعية مؤتمتة"),
        short: m("KPIs from all your tools, summarized every Monday morning.", "Vos KPIs de tous vos outils, résumés chaque lundi matin.", "مؤشرات كل أدواتك ملخصة كل صباح اثنين."),
        description: m("Sales, marketing, support and social metrics are collected, compared to targets, and delivered as one clean digest to your leadership.", "Les métriques vente, marketing, support et social sont collectées, comparées aux objectifs et livrées en une synthèse propre à votre direction.", "تُجمع مؤشرات المبيعات والتسويق والدعم والتواصل، وتقارن بالأهداف، وتسلَّم كملخص واحد أنيق لإدارتك."),
        benefits: [m("One digest, all tools", "Une synthèse, tous les outils", "ملخص واحد لكل الأدوات"), m("Targets vs actuals", "Objectifs vs réalisations", "الأهداف مقابل النتائج"), m("Monday, 8:00, always", "Lundi, 8 h, toujours", "الاثنين، الثامنة، دائمًا")],
        workflow: [m("Tool sync", "Synchronisation", "مزامنة الأدوات"), m("KPI aggregation", "Agrégation des KPIs", "تجميع المؤشرات"), m("Variance analysis", "Analyse des écarts", "تحليل الفروقات"), m("Digest build", "Création de la synthèse", "بناء الملخص"), m("Email / Slack send", "Envoi e-mail / Slack", "إرسال بريد / Slack")],
        integrations: ["Stripe", "HubSpot", "Meta", "Slack"], order: 11, active: true,
      },
    ],
    socialPage: {
      heroBadge: m("Social Media Management", "Gestion des réseaux sociaux", "إدارة وسائل التواصل"),
      heroTitle: m("Social Media Management That Works Like a System.", "Une gestion des réseaux sociaux qui fonctionne comme un système.", "إدارة تواصل اجتماعي تعمل كنظام متكامل."),
      heroDescription: m("Strategy, content, community management, scheduling, and analytics — organized into a system built around your business.", "Stratégie, contenu, communauté, planification et analytique — organisés en un système construit autour de votre entreprise.", "استراتيجية ومحتوى وإدارة مجتمع وجدولة وتحليلات — منظمة في نظام يُبنى حول نشاطك."),
      primaryCta: m("View Packages", "Voir les offres", "عرض الباقات"),
      secondaryCta: m("Talk to FLUXMEDIA", "Parler à FLUXMEDIA", "تحدث مع FLUXMEDIA"),
      servicesTitle: m("Everything Your Presence Needs", "Tout ce dont votre présence a besoin", "كل ما يحتاجه حضورك"),
      servicesDescription: m("Eight disciplines, run as one coordinated system.", "Huit expertises, menées comme un seul système coordonné.", "ثمانية تخصصات تُدار كنظام واحد منسق."),
      services: [
        { id: "s1", icon: "compass", order: 1, title: m("Content Strategy", "Stratégie de contenu", "استراتيجية المحتوى"), description: m("Positioning, pillars, tone of voice and a plan that matches your goals.", "Positionnement, piliers, ton et plan alignés sur vos objectifs.", "تموضع وركائز ونبرة وخطة توافق أهدافك."), deliverables: [m("Audit & positioning", "Audit & positionnement", "تدقيق وتموضع"), m("Content pillars", "Piliers de contenu", "ركائز المحتوى"), m("Quarterly roadmap", "Feuille de route trimestrielle", "خطة ربع سنوية")] },
        { id: "s2", icon: "pen", order: 2, title: m("Content Creation", "Création de contenu", "إنتاج المحتوى"), description: m("Design, video and copy produced for your brand, ready to publish.", "Design, vidéo et textes produits pour votre marque, prêts à publier.", "تصميم وفيديو ونصوص تُنتج لعلامتك وجاهزة للنشر."), deliverables: [m("Visual designs", "Visuels design", "تصاميم بصرية"), m("Captions & hooks", "Légendes & accroches", "تعليقات وافتتاحيات"), m("Brand-consistent assets", "Assets cohérents avec la marque", "أصول متسقة مع العلامة")] },
        { id: "s3", icon: "dashboard", order: 3, title: m("Social Media Management", "Gestion des réseaux sociaux", "إدارة الحسابات"), description: m("Your accounts run daily: publishing, monitoring, and coordination.", "Vos comptes gérés au quotidien : publication, veille, coordination.", "حساباتك تُدار يوميًا: نشر ومراقبة وتنسيق."), deliverables: [m("Account management", "Gestion des comptes", "إدارة الحسابات"), m("Publishing & monitoring", "Publication & veille", "نشر ومراقبة"), m("Monthly coordination call", "Point mensuel", "لقاء تنسيقي شهري")] },
        { id: "s4", icon: "video", order: 4, title: m("Reels & Short-Form Content", "Reels & formats courts", "ريلز ومحتوى قصير"), description: m("Short-form video planned, edited and packaged for reach.", "Vidéos courtes planifiées, montées et packagées pour la portée.", "فيديو قصير يُخطط ويمنتج ويجهز للوصول."), deliverables: [m("Reels concepts", "Concepts de reels", "أفكار ريلز"), m("Editing & captions", "Montage & sous-titres", "مونتاج وترجمة"), m("Trend adaptation", "Adaptation des tendances", "مواكبة الاتجاهات")] },
        { id: "s5", icon: "users", order: 5, title: m("Community Management", "Gestion de communauté", "إدارة المجتمع"), description: m("Comments and DMs answered in your tone, leads flagged instantly.", "Commentaires et DMs répondus dans votre ton, leads signalés aussitôt.", "ردود على التعليقات والرسائل بنبرتك، وإشارة فورية للعملاء."), deliverables: [m("Comment & DM handling", "Réponses commentaires & DMs", "ردود على التعليقات والرسائل"), m("Escalation rules", "Règles d'escalade", "قواعد تصعيد"), m("Sentiment notes", "Notes de sentiment", "ملاحظات الانطباع")] },
        { id: "s6", icon: "calendar", order: 6, title: m("Content Scheduling", "Planification du contenu", "جدولة المحتوى"), description: m("A calendar you can see, with the right post at the right time.", "Un calendrier visible, avec le bon post au bon moment.", "تقويم واضح بمنشور مناسب في وقت مناسب."), deliverables: [m("Monthly calendar", "Calendrier mensuel", "تقويم شهري"), m("Best-time scheduling", "Planification aux meilleurs créneaux", "جدولة بأفضل الأوقات"), m("Approvals workflow", "Circuit de validation", "مسار اعتماد")] },
        { id: "s7", icon: "chart", order: 7, title: m("Social Media Analytics", "Analytique des réseaux sociaux", "تحليلات التواصل"), description: m("Clear reports: what grew, what worked, what we change next.", "Rapports clairs : croissance, ce qui marche, ce qu'on change.", "تقارير واضحة: ما نما وما نجح وما سنغيره."), deliverables: [m("Monthly report", "Rapport mensuel", "تقرير شهري"), m("KPI tracking", "Suivi des KPIs", "تتبع المؤشرات"), m("Next-month actions", "Actions du mois suivant", "إجراءات الشهر التالي")] },
        { id: "s8", icon: "trend", order: 8, title: m("Social Lead Generation", "Génération de leads sociale", "توليد عملاء من التواصل"), description: m("Content and DM flows designed to turn attention into inquiries.", "Contenus et flux DM conçus pour transformer l'attention en demandes.", "محتوى ومسارات رسائل تحوّل الانتباه إلى استفسارات."), deliverables: [m("Lead magnets", "Aimants à leads", "موارد جاذبة"), m("DM funnels", "Entonnoirs DM", "مسارات رسائل"), m("CRM handoff", "Transfert au CRM", "تسليم إلى CRM")] },
      ],
      platformsTitle: m("Platforms We Manage", "Plateformes que nous gérons", "المنصات التي نديرها"),
      platformsDescription: m("One system across every channel your audience uses.", "Un seul système sur tous les canaux que votre audience utilise.", "نظام واحد عبر كل القنوات التي يستخدمها جمهورك."),
      platforms: ["instagram", "facebook", "linkedin", "tiktok", "youtube", "x"],
      packagesTitle: m("Social Media Packages", "Offres réseaux sociaux", "باقات التواصل الاجتماعي"),
      packagesDescription: m("Transparent scopes. Editable by FLUXMEDIA at any time — what you see is what we deliver.", "Périmètres transparents, modifiables par FLUXMEDIA à tout moment — ce que vous voyez est ce que nous livrons.", "نطاقات شفافة وقابلة للتحديث — ما تراه هو ما نقدمه."),
      processTitle: m("How We Run Your Social Media", "Comment nous gérons vos réseaux", "كيف ندير تواصلك"),
      processDescription: m("A steady operating rhythm, every month.", "Un rythme opérationnel régulier, chaque mois.", "إيقاع تشغيلي منتظم كل شهر."),
      processSteps: [
        { id: "p1", title: m("Audit & Strategy", "Audit & stratégie", "تدقيق واستراتيجية"), description: m("We audit your accounts and define positioning, pillars and targets.", "Nous auditons vos comptes et définissons positionnement, piliers et objectifs.", "ندقق حساباتك ونحدد التموضع والركائز والأهداف.") },
        { id: "p2", title: m("Content Plan", "Plan de contenu", "خطة المحتوى"), description: m("A monthly calendar with formats, hooks and publishing times.", "Un calendrier mensuel avec formats, accroches et horaires.", "تقويم شهري بصيغ وافتتاحيات وأوقات نشر.") },
        { id: "p3", title: m("Production", "Production", "إنتاج"), description: m("Design, video and copy produced and approved by you.", "Design, vidéo et textes produits et validés par vous.", "إنتاج تصميم وفيديو ونصوص تعتمدها أنت.") },
        { id: "p4", title: m("Publish & Engage", "Publication & engagement", "نشر وتفاعل"), description: m("We schedule, publish, and manage comments and DMs.", "Nous planifions, publions et gérons commentaires et DMs.", "نجدول وننشر وندير التعليقات والرسائل.") },
        { id: "p5", title: m("Report & Optimize", "Rapport & optimisation", "تقرير وتحسين"), description: m("Monthly analytics and next-month improvements.", "Analytique mensuelle et améliorations du mois suivant.", "تحليلات شهرية وتحسينات للشهر التالي.") },
      ],
      finalCtaTitle: m("Let's Build Your Social System.", "Construisons votre système social.", "لنبنِ نظام تواصلك."),
      finalCtaDescription: m("Pick a package or talk to us first — we'll scope the right fit for your business.", "Choisissez une offre ou parlons d'abord — nous cadrerons la bonne solution.", "اختر باقة أو تحدث معنا أولًا — سنحدد الأنسب لنشاطك."),
      finalCtaPrimary: m("View Packages", "Voir les offres", "عرض الباقات"),
      finalCtaSecondary: m("Talk to FLUXMEDIA", "Parler à FLUXMEDIA", "تحدث مع FLUXMEDIA"),
    },
    packages: [
      {
        id: "pk1", slug: "starter", name: "Starter", price: 490, currency: "USD",
        description: m("For businesses that need a consistent social presence.", "Pour les entreprises qui ont besoin d'une présence sociale régulière.", "للأنشطة التي تحتاج حضورًا منتظمًا على وسائل التواصل."),
        billingPeriod: m("per month", "par mois", "شهريًا"), badge: m("", "", ""), popular: false, visible: true, order: 1,
        features: [
          { id: "f1", order: 1, text: m("Content strategy", "Stratégie de contenu", "استراتيجية المحتوى") },
          { id: "f2", order: 2, text: m("Monthly content calendar", "Calendrier de contenu mensuel", "تقويم محتوى شهري") },
          { id: "f3", order: 3, text: m("12 posts / month", "12 publications / mois", "12 منشورًا / شهريًا") },
          { id: "f4", order: 4, text: m("8 stories / month", "8 stories / mois", "8 ستوري / شهريًا") },
          { id: "f5", order: 5, text: m("Captions & hashtags", "Légendes & hashtags", "تعليقات ووسوم") },
          { id: "f6", order: 6, text: m("Basic monthly reporting", "Rapport mensuel de base", "تقرير شهري أساسي") },
        ],
        postsPerMonth: 12, reelsPerMonth: 0, storiesPerMonth: 8,
        platforms: ["instagram", "facebook"],
      },
      {
        id: "pk2", slug: "growth", name: "Growth", price: 890, currency: "USD",
        description: m("For businesses that want consistent content and active growth.", "Pour les entreprises qui veulent un contenu régulier et une croissance active.", "للأنشطة التي تريد محتوى منتظمًا ونموًا فعالًا."),
        billingPeriod: m("per month", "par mois", "شهريًا"), badge: m("", "", ""), popular: true, visible: true, order: 2,
        features: [
          { id: "f1", order: 1, text: m("Everything in Starter", "Tout Starter inclus", "كل مزايا Starter") },
          { id: "f2", order: 2, text: m("20 posts / month", "20 publications / mois", "20 منشورًا / شهريًا") },
          { id: "f3", order: 3, text: m("8 reels / month", "8 reels / mois", "8 ريلز / شهريًا") },
          { id: "f4", order: 4, text: m("16 stories / month", "16 stories / mois", "16 ستوري / شهريًا") },
          { id: "f5", order: 5, text: m("Community management", "Gestion de communauté", "إدارة المجتمع") },
          { id: "f6", order: 6, text: m("Analytics & monthly optimization", "Analytique & optimisation mensuelle", "تحليلات وتحسين شهري") },
        ],
        postsPerMonth: 20, reelsPerMonth: 8, storiesPerMonth: 16,
        platforms: ["instagram", "facebook", "tiktok"],
      },
      {
        id: "pk3", slug: "pro", name: "Pro", price: 1490, currency: "USD",
        description: m("For businesses that want a complete social media management system.", "Pour les entreprises qui veulent un système complet de gestion sociale.", "للأنشطة التي تريد نظام إدارة تواصل متكاملًا."),
        billingPeriod: m("per month", "par mois", "شهريًا"), badge: m("", "", ""), popular: false, visible: true, order: 3,
        features: [
          { id: "f1", order: 1, text: m("Full strategy & content creation", "Stratégie complète & création", "استراتيجية كاملة وإنتاج محتوى") },
          { id: "f2", order: 2, text: m("30 posts / month", "30 publications / mois", "30 منشورًا / شهريًا") },
          { id: "f3", order: 3, text: m("12 reels / month", "12 reels / mois", "12 ريلز / شهريًا") },
          { id: "f4", order: 4, text: m("30 stories / month", "30 stories / mois", "30 ستوري / شهريًا") },
          { id: "f5", order: 5, text: m("Community management", "Gestion de communauté", "إدارة المجتمع") },
          { id: "f6", order: 6, text: m("Multi-platform management", "Gestion multi-plateformes", "إدارة متعددة المنصات") },
          { id: "f7", order: 7, text: m("Lead-focused content", "Contenu orienté leads", "محتوى موجّه للعملاء") },
          { id: "f8", order: 8, text: m("Monthly strategy review", "Revue stratégique mensuelle", "مراجعة استراتيجية شهرية") },
        ],
        postsPerMonth: 30, reelsPerMonth: 12, storiesPerMonth: 30,
        platforms: ["instagram", "facebook", "tiktok", "linkedin", "youtube", "x"],
      },
    ],
    socialLinks: [
      { id: "l1", platform: "instagram", name: "Instagram", username: "@fluxmedia", description: m("Follow us on Instagram", "Suivez-nous sur Instagram", "تابعنا على إنستغرام"), url: "https://instagram.com/fluxmedia", active: true, order: 1 },
      { id: "l2", platform: "facebook", name: "Facebook", username: "FLUXMEDIA", description: m("Follow our Facebook page", "Suivez notre page Facebook", "تابع صفحتنا على فيسبوك"), url: "https://facebook.com/fluxmedia", active: true, order: 2 },
      { id: "l3", platform: "whatsapp", name: "WhatsApp", username: "+212 6 00 00 00 00", description: m("Chat with FLUXMEDIA", "Discutez avec FLUXMEDIA", "تحدث مع FLUXMEDIA"), url: "https://wa.me/212600000000", active: true, order: 3 },
      { id: "l4", platform: "linkedin", name: "LinkedIn", username: "FLUXMEDIA", description: m("Connect with us on LinkedIn", "Connectez-vous sur LinkedIn", "تواصل معنا على لينكدإن"), url: "https://linkedin.com/company/fluxmedia", active: true, order: 4 },
      { id: "l5", platform: "x", name: "X / Twitter", username: "@fluxmedia", description: m("Follow us on X", "Suivez-nous sur X", "تابعنا على إكس"), url: "https://x.com/fluxmedia", active: true, order: 5 },
      { id: "l6", platform: "website", name: "Website", username: "fluxmedia.agency", description: m("Explore the FLUXMEDIA website", "Explorez le site FLUXMEDIA", "استكشف موقع FLUXMEDIA"), url: "https://fluxmedia.agency", active: true, order: 6 },
    ],
    faqs: [
      { id: "q1", order: 1, visible: true, question: m("Do you create the content or do we?", "Créez-vous le contenu ou nous ?", "هل تنتجون المحتوى أم نحن؟"), answer: m("We produce it — design, video and copy. Your input on brand voice and offers makes it sharper.", "Nous le produisons : design, vidéo et textes. Vos retours sur la voix de marque et les offres l'affinent.", "ننتجه نحن — تصميم وفيديو ونصوص. ومدخلاتك حول نبرة العلامة والعروض تجوده.") },
      { id: "q2", order: 2, visible: true, question: m("How fast can we start?", "À quelle vitesse pouvons-nous démarrer ?", "متى يمكننا البدء؟"), answer: m("Onboarding takes about one week: audit, strategy, access setup, then the first calendar.", "L'intégration prend environ une semaine : audit, stratégie, accès, puis premier calendrier.", "يستغرق البدء أسبوعًا تقريبًا: تدقيق واستراتيجية وتجهيز الوصول ثم أول تقويم.") },
      { id: "q3", order: 3, visible: true, question: m("Are there long-term contracts?", "Y a-t-il des contrats longue durée ?", "هل توجد عقود طويلة الأجل؟"), answer: m("No. Packages are monthly with 30 days notice. We keep clients with results, not lock-in.", "Non. Les offres sont mensuelles avec préavis de 30 jours. Nous gardons les clients par les résultats.", "لا. الباقات شهرية بإشعار 30 يومًا. نُبقي العملاء بالنتائج لا بالالتزام.") },
      { id: "q4", order: 4, visible: true, question: m("Can we combine a package with automation?", "Peut-on combiner une offre avec l'automatisation ?", "هل يمكن دمج باقة مع الأتمتة؟"), answer: m("Yes — that's the FLUXMEDIA model. Social brings attention; automation turns it into tracked, followed-up business.", "Oui — c'est le modèle FLUXMEDIA. Le social attire l'attention ; l'automatisation la transforme en business suivi.", "نعم — هذا نموذج FLUXMEDIA. التواصل يجلب الانتباه والأتمتة تحوّله إلى أعمال متتبعة.") },
      { id: "q5", order: 5, visible: true, question: m("Which platforms do you manage?", "Quelles plateformes gérez-vous ?", "ما المنصات التي تديرونها؟"), answer: m("Instagram, Facebook, LinkedIn, TikTok, YouTube and X — depending on where your audience lives.", "Instagram, Facebook, LinkedIn, TikTok, YouTube et X — selon là où vit votre audience.", "إنستغرام وفيسبوك ولينكدإن وتيك توك ويوتيوب وإكس — حسب مكان وجود جمهورك.") },
      { id: "q6", order: 6, visible: true, question: m("Do you run paid ads?", "Gérez-vous les publicités payantes ?", "هل تديرون الإعلانات المدفوعة؟"), answer: m("Our core is organic management. Paid campaigns can be scoped as an add-on when it makes sense.", "Notre cœur est la gestion organique. Les campagnes payantes peuvent s'ajouter si pertinent.", "أساسنا الإدارة العضوية. يمكن إضافة حملات مدفوعة عند الحاجة.") },
    ],
    requests: [],
    messages: [],
    posts: [
      { id: "po1", client: "Atlas Roasters", platform: "instagram", caption: "Morning pour-over ritual — single origin Azrou.", media: "reel", contentType: "Reel", campaign: "Origins", status: "published", scheduleDate: "2026-09-14" },
      { id: "po2", client: "Atlas Roasters", platform: "instagram", caption: "Latte art championship announcement.", media: "image", contentType: "Post", campaign: "Brand", status: "scheduled", scheduleDate: "2026-09-19" },
      { id: "po3", client: "Nordic Fit", platform: "tiktok", caption: "3 mistakes on the deadlift.", media: "video", contentType: "Reel", campaign: "Coaching", status: "scheduled", scheduleDate: "2026-09-20" },
      { id: "po4", client: "Nordic Fit", platform: "instagram", caption: "Member story: 6 months transformation.", media: "carousel", contentType: "Carousel", campaign: "Stories", status: "review", scheduleDate: "2026-09-22" },
      { id: "po5", client: "Sahara Tours", platform: "facebook", caption: "October desert departures now open.", media: "image", contentType: "Post", campaign: "Season", status: "approved", scheduleDate: "2026-09-23" },
      { id: "po6", client: "Sahara Tours", platform: "instagram", caption: "Campfire nights — dunes of Merzouga.", media: "reel", contentType: "Reel", campaign: "Season", status: "draft", scheduleDate: "2026-09-25" },
      { id: "po7", client: "Atlas Roasters", platform: "linkedin", caption: "How we source from Azrou cooperatives.", media: "image", contentType: "Post", campaign: "Origins", status: "scheduled", scheduleDate: "2026-09-21" },
      { id: "po8", client: "Nordic Fit", platform: "instagram", caption: "Friday community WOD — join us.", media: "story", contentType: "Story", campaign: "Community", status: "published", scheduleDate: "2026-09-18" },
    ],
    inbox: [
      { id: "i1", platform: "instagram", author: "Yassine E.", handle: "@yassine.e", body: "Do you ship beans to Casablanca? Also interested in a subscription.", category: "lead", unread: true, createdAt: "2026-09-18T09:12:00Z", suggestedReply: "Yes — we ship nationwide! A subscription gets you free shipping. Want me to send the link?" },
      { id: "i2", platform: "instagram", author: "Sara M.", handle: "@sara.m", body: "What time do you open on Sundays?", category: "question", unread: true, createdAt: "2026-09-18T08:40:00Z", suggestedReply: "We're open Sundays 9:00–14:00. See you there!" },
      { id: "i3", platform: "facebook", author: "Karim B.", handle: "Karim Benali", body: "I sent an order twice and no confirmation email.", category: "support", unread: false, createdAt: "2026-09-17T18:22:00Z", suggestedReply: "Sorry about that — checking your order now, you'll receive confirmation within the hour." },
      { id: "i4", platform: "tiktok", author: "lina.fits", handle: "@lina.fits", body: "Price for 3 months personal coaching?", category: "sales", unread: true, createdAt: "2026-09-17T14:05:00Z", suggestedReply: "Great question — our 3-month coaching plan is 2,400 MAD with a free assessment week. Want to book it?" },
      { id: "i5", platform: "instagram", author: "promo.deals", handle: "@promo.deals", body: "Collab? We promote brands to 2M followers.", category: "spam", unread: false, createdAt: "2026-09-16T11:00:00Z", suggestedReply: "" },
      { id: "i6", platform: "linkedin", author: "H. Alaoui", handle: "Hind Alaoui", body: "We're looking for a social media partner for our riad group.", category: "lead", unread: true, createdAt: "2026-09-16T09:30:00Z", suggestedReply: "We'd love to help — could we schedule a 20-minute call this week to scope your needs?" },
    ],
    clients: [
      { id: "cl1", name: "Atlas Roasters", industry: "Specialty coffee", platforms: ["instagram", "facebook", "linkedin"], packageSlug: "growth", since: "2026-03", status: "active" },
      { id: "cl2", name: "Nordic Fit", industry: "Fitness studio", platforms: ["instagram", "tiktok"], packageSlug: "pro", since: "2026-05", status: "active" },
      { id: "cl3", name: "Sahara Tours", industry: "Tourism", platforms: ["facebook", "instagram"], packageSlug: "starter", since: "2026-07", status: "active" },
    ],
    accounts: [
      { id: "ac1", platform: "instagram", handle: "@atlasroasters", client: "Atlas Roasters", connected: false, note: "Managed via business suite — API connection pending" },
      { id: "ac2", platform: "instagram", handle: "@nordicfit.ma", client: "Nordic Fit", connected: false, note: "Managed via business suite" },
      { id: "ac3", platform: "facebook", handle: "Sahara Tours", client: "Sahara Tours", connected: false, note: "Page access granted" },
      { id: "ac4", platform: "tiktok", handle: "@nordicfit.ma", client: "Nordic Fit", connected: false, note: "Creator access" },
    ],
  };
}
